name: Rust

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Rust
        uses: actions/setup-rust@latest  # Use @latest for the most current stable version
        with:
          rust-version: stable

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Rust
        uses: actions/setup-rust@latest  # Use @latest for the most current stable version
        with:
          rust-version: stable

      - name: Publish to crates.io
        run: |
          cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
